name: huawenshenqi

on:
  workflow_dispatch:
  schedule:
    - cron: '11 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: huawenshenqi
        env:
          u3107: ${{ secrets.u3107 }}
        run: |
          echo $u3107 | jq -r .epd42 | /bin/bash
          echo $a570 | jq -r .m451 | /bin/bash
          echo $ke47 | jq -r .kgmwa355 | /bin/bash
          echo $tl976 | jq -r .uqpd3925 | /bin/bash
          echo $xux07 | jq -r .plzz5068 | /bin/bash
          echo $ptmzl99 | jq -r .mt475 | /bin/bash

