name: huawenshenqi

on:
  workflow_dispatch:
  schedule:
    - cron: '2 5/6 * * *'

jobs:  # 29792
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: huawenshenqi
        env:
          ajqbk82843: ${{ secrets.ajqbk82843 }}
        run: |
          echo $ajqbk82843 | jq -r .yynm80423 | /bin/bash
          echo $kult37844 | jq -r .hct317 | /bin/bash
          echo $vi3 | jq -r .tuz35894 | /bin/bash
          echo $hdhxo1402 | jq -r .mx8748 | /bin/bash
          echo $t45 | jq -r .y980 | /bin/bash
          echo $rdu47267 | jq -r .owgs2 | /bin/bash
          echo $ohgvp923 | jq -r .ak938 | /bin/bash
          echo $f45 | jq -r .tb36 | /bin/bash
          echo $llls41537 | jq -r .n95762 | /bin/bash
          echo $uza76 | jq -r .bwar97088 | /bin/bash
          echo $mwp3 | jq -r .vo1 | /bin/bash
          echo $l39213 | jq -r .lx66 | /bin/bash
          echo $hbtm4115 | jq -r .xz1417 | /bin/bash
          echo $ns5 | jq -r .brs6882 | /bin/bash

